# Generated by Django 5.0.3 on 2024-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningLogApp', '0004_assunto_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='status',
            field=models.CharField(choices=[('PD', 'Pendente'), ('EP', 'Em progresso'), ('FT', 'Feito')], default='PD', max_length=2),
        ),
    ]
